[package]
name = "bevy-earth"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3", features = ["bevy_dev_tools" ] }
bevy-inspector-egui = "0.35.0"
bevy_egui = "0.38.0"
egui_extras = { version = "0.33.2", features = ["gif"] }
image = "0.25.9"
